### ISSUE TITLE
Unable to store estimator in Jupyter notebook

### ISSUE THREAD

**Issue by gcasamat** [microsoft/EconML#381]
I used to store an estimator using the %store command in a Jupyter notebook, and retrieve it in another notebook with %store -r. The estimator was defined as follows: 
```
est_forest_gb = ForestDML(
                            model_y = GradientBoostingRegressor(n_estimators = 200, random_state = 42), 
                            model_t = GradientBoostingRegressor(n_estimators = 200, random_state = 42), 
                            n_estimators = 200,
                            cv = [(fold0, fold1), (fold1, fold0)],
                            random_state = 123)
```
I have now moved to the new CausalForestDML and the %store -r command now sends me:
```
Unable to restore variable 'best_algo', ignoring (use %store -d to forget!)
The error was: <class 'KeyError'>
```
Note that I still can use the %store command with the old ForestDML

**Comment by vsyrgkanis** [comment]
This seems a bug in the new cython Tree code. Will fix by 0.9 (in a week or so).

**Comment by vsyrgkanis** [comment]
Can you try cloning the vasilis/fix_pickle_grf branch and install that branch,  by running at the root folder of the clone:
`python setup.py develop` 

This should fix the problem. It should soon be in the master and the release, but would be great if you could test it ahead of time.

**Comment by gcasamat** [comment]
I tried, and the problem persists. 
However, you should not be 100% confident in my skills to perform that kind of operations ;) [what I did is to clone your repository and replace the directory econml in anaconda3/lib/python3.8/site-packages ]

**Comment by kbattocchi** [comment]
@gcasamat - The fixing change has now been merged into master, but still won't be publicly released for a week or so.  If you'd like to use it in the meantime, could you try the following?

1. Run `pip uninstall econml` to get rid of your existing installation (maybe try running this twice in case you've somehow got more than one installation already)
2. Run `pip install -e git+https://github.com/microsoft/EconML.git@master` to install econml from github

**Comment by gcasamat** [comment]
I tried to do what you suggest, but I got the following error message:
`ERROR: Could not detect requirement name for 'git+https://github.com/microsoft/EconML.git@master', please specify one with #egg=your_package_name`

**Comment by kbattocchi** [comment]
Okay, try adding #egg=econml to the end of the url.

**Comment by gcasamat** [comment]
I got the following error message when executing my code
`ModuleNotFoundError: No module named 'sklearn.base'`
(by the way, have you noticed that pandas is downgraded each time econml is being installed)

**Comment by kbattocchi** [comment]
@gcasamat Regarding pandas, I believe that will be addressed by #383, which will also be included in next week's release.  Not sure what's going on with the sklearn error - what version of sklearn do you have installed?

**Comment by gcasamat** [comment]
I have version 0.24.1 of sklearn

**Comment by gcasamat** [comment]
I managed to solve the problem. Everything works fine now. Thank you!
